### ISSUE TITLE
Midi sync is not starting from the first time

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#10]
I have following problem when starting MIDI sync from network MIDI session. Despite the fact, that Afterglow sees messages, it doesn't want to start sync. 

https://gist.github.com/dandaka/dd5963c5c700ca3ff7ea

Source is here:

https://github.com/dandaka/lights-experiment/blob/master/src/lights/my_show.clj#L169

If this is a problem from other libraries, plz let me know, where to look.

**Comment by brunchboy** [comment]
I have a suspicion about what might be going on here. Could you try calling
```clojure
(afterglow.midi/open-inputs-if-needed!)
```
and waiting a few seconds before trying your `(sync-midi-clock)`? Your code looks fine to me, and I think that when I rewrote my MIDI clock finder code to be more efficient (by always running in the background), I also inadvertently got rid of the code which used to call this for you, which breaks the examples. I did not notice this because I have always been using either the Ableton Push or Web interfaces, and both of those open the MIDI inputs.

**Comment by brunchboy** [comment]
Yes, that looks likely to be your problem. I looked at an older version of `sync-to-midi-clock`. It used to call `watch-for-clock-sources`, which called `open-inputs-if-needed!` but in the current version, clock sources are always watched for in the background, so `watch-for-clock-sources` was removed. Unfortunately, that also removed the call to `open-inputs-if-needed!`, so you probably had no MIDI devices hooked up in Afterglow. I just deployed a new snapshot build that calls `open-inputs-if-needed!` directly from `sync-to-midi-clock`, so they will be opened if necessary. Hopefully this will make it work for you even in cases where you’ve not connected the MIDI inputs before calling it.

This new snapshot seems to work properly for me even if trying to sync to a MIDI clock is the first thing I do after creating the show. Before making this change, I was able to reproduce what looked like your problem if I did that without connecting a MIDI controller or starting up the web UI. (There is now a pause the first time you call `sync-to-midi-clock` if the Java MIDI environment was not yet set up.)

If it still doesn't work, what does `(afterglow.midi/current-clock-sources)` show? Here is what it looks like for me, with Traktor running:

```clojure
#{{:name "Traktor Virtual Output", :description "Traktor Virtual Output", :vendor "Unknown vendor",
   :version "Unknown version", :sources 2147483647, :sinks 0,
   :info #object[com.sun.media.sound.MidiInDeviceProvider$MidiInDeviceInfo 0x4aea4615 "Traktor Virtual Output"],
   :device #object[com.sun.media.sound.MidiInDevice 0x4c49f034 "com.sun.media.sound.MidiInDevice@4c49f034"],
   :transmitter #object[com.sun.media.sound.MidiInDevice$MidiInTransmitter 0x69b8fb55
    "com.sun.media.sound.MidiInDevice$MidiInTransmitter@69b8fb55"]}}
```

When you pull the latest version of `[afterglow "0.1.6-SNAPSHOT"]` you should also edit your `project.clj` to depend on the latest release candidate of Clojure 1.8, because I am now building and testing Afterglow against that: replace `[org.clojure/clojure "1.7.0"]` with `[org.clojure/clojure "1.8.0-RC3"]`

**Comment by dandaka** [comment]
Working with latest versions, thank you!

**Comment by brunchboy** [comment]
Great! Sorry about that.
