### ISSUE TITLE
(:metronome sample-show) returns nil

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#11]
I try to reset metronome from this tutorial

https://github.com/brunchboy/afterglow/blob/master/doc/metronomes.adoc#metronomes

First example is now working as expected:

```
lights.my-show=> (:metronome my-show)
(:metronome my-show)
nil
```

Is it me or Afterglow?

**Comment by brunchboy** [comment]
I don’t have enough context to answer this, is your project on github up to date? If your `my-show` var has an actual show in it, then the code snippet should return its metronome. So something else must be wrong.

**Comment by brunchboy** [comment]
I went over to take a look at your lights-experiment project, and I think I may know what your problem is. Assuming you called [use-my-show](https://github.com/dandaka/lights-experiment/blob/master/src/lights/my_show.clj#L79) then your `my-show` atom will contain a show, which will contain a metronome. However, when you write

```clojure
(:metronome my-show)
```
you are asking Clojure to find the key `:metronome` directly in the atom, rather than in the value the atom refers to, and so it is finding nothing. This would work better:

```clojure
(:metronome @my-show)
```
> This version dereferences the atom to get its current value, and then looks up the `:metronome` keyword within that. The `@` is Clojure reader shorthand for calling the `deref` function, so the line is also equivalent to writing `(:metronome (deref my-show))`.

Because `use-my-show` also sets up the show pointed to by `@my-show` as the Afterglow default show, and your `lights.my-show` namespace refers to the vars defined in `afterglow.show-context`, you can also get at your show via the `*show*` var directly, like so:
```clojure
(:metronome *show*)
```

Try one (or both) of those approaches, and see if they work better for you, and please let me know!

**Comment by dandaka** [comment]
I think documentation with working examples could be a big help for newbees like me. If this change is out of style or something, please let me know.

**Comment by brunchboy** [comment]
Your change was perfect! My examples used to work, but they became stale when I introduced the `afterglow.show-context` namespace as a better way of maintaining the notion of the current show.
