### ISSUE TITLE
Cue launching custom function?

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#21]
Is it possible to use cue to launch custom function? I have looked through documentation, can't find any example yet. All examples I see attach 1 effect, which is asking for more.

1) For example, I have a basic function, that can receive `beat-ratio` to make animation slower or faster:

```
(defn light-sawtooth
  "Change light according to sawtooth osc"
  [beat-ratio]
  (let [light-param (params/build-oscillated-param
    (oscillators/sawtooth-beat :beat-ratio beat-ratio :down? true) :max :max-lightness)]
    (show/add-effect! :color (global-color-effect
      (params/build-color-param :h :main-hue :s 100 :l light-param)))
  )
)
```

I want to launch this function with different parameters from Cue Grid. One effect is not enough, since I have few groups of fixtures. And it is nice to control all these groups from one button in Cue Grid.

2) Also it would be nice to control variables from Cue Grid. It is essentially same functionality, I just want to show you user cases for this.

I have `main-hue` variable, and all other functions and effects are linked to it. No need to specify color on each effect, more flexibility. And its possible to control show color from external sources (say MIDI).

```
(afterglow.show/set-variable! :main-hue 0)
```

**Comment by brunchboy** [comment]
Cues have to create effects, but those effects can be degenerate and really do something else. I do have an example somewhere already of an effect which sets a variable, and a cue that uses that. I don’t have time to point you at it right now, but will leave this issue open until I can this weekend.

**Comment by brunchboy** [comment]
Rats! I thought I had posted an update to this on Friday midday, I wrote it all up and thought I submitted it, but now it is not here! I must have hit `Preview` but never `Comment`, whoops.

There is definitely a way to do this, I needed it myself for one of my shows, where I wanted to have the color of a laser that did not use DMX track the color of some other lights, and I found the documentation: The [Variable Effect](https://github.com/brunchboy/afterglow/blob/master/doc/effects.adoc#variable-effects) will do exactly what you want.

**Comment by brunchboy** [comment]
Another thing you might want to look at is the [Conditional Effect](https://github.com/brunchboy/afterglow/blob/master/doc/effects.adoc#conditional-effects) which wraps another effect, so that the inner effect only runs when the value of the conditional effect’s dynamic parameter is not zero. And remember that a cue can launch a [scene](https://github.com/brunchboy/afterglow/blob/master/doc/effects.adoc#scenes) which can contain any number of effects.

**Comment by dandaka** [comment]
How can a cue launch a scene? Can you show an example? Can't find it anywhere.

My first guess was like 

```
(ct/set-cue! (:cue-grid *show*) 0 18
    (afterglow.effects/scene "Blue Sparks"
      (global-color-effect :blue)
      (fun/sparkle (show/all-fixtures) :chance 0.07 :fade-time 500))
    )
```

and its not working.

**Comment by brunchboy** [comment]
That is close, but missing a couple of details. It looks like your code to create the scene is right, but the first problem is that you are trying to create the scene effect and pass that to the cue grid directly. You need to create a cue that creates that effect, and pass the *cue* to `set-cue!`.

> Also note that when creating a cue, you don’t pass [afterglow.effects.cue](http://deepsymmetry.org/afterglow/doc/afterglow.effects.cues.html#var-cue) an existing effect: `cue` takes a *function* that will create the effect when the cue is launched, because there may be aspects of an effect that get determined when the effect gets created, so the cue wants to start with a fresh instance of the effect each time you launch the cue.

As a quick attempt to fix your code, I think what you want is:
```clojure
(ct/set-cue! (:cue-grid *show*) 0 18
             (cues/cue :color  (fn [_] (afterglow.effects/scene
                                        "Blue Sparks"
                                        (global-color-effect :blue)
                                        (fun/sparkle (show/all-fixtures)
                                                     :chance 0.07 :fade-time 500)))))
```

In this case, since the function that creates the effect does not need to to create any temporary show variables and pass them in to the effect, it ignores its single argument. (The convention in Clojure is to use `_` as the name for an argument that you ignore.) There are examples of using temporary show variables with cues elsewhere in `examples.clj`, but we do not need that complexity here.

Since scenes are so new there are not many examples yet. The `try-laser-cues` function in `examples.clj` builds [a cue that creates one](https://github.com/brunchboy/afterglow/blob/master/src/afterglow/examples.clj#L313-L318). In `shows/sallie.clj` you might also be interested in [global-color-effect](https://github.com/brunchboy/afterglow/blob/master/src/afterglow/shows/sallie.clj#L81-L101) as an example of a scene that includes a conditional effect, and then [global-color-cue](https://github.com/brunchboy/afterglow/blob/master/src/afterglow/shows/sallie.clj#L112-L118) shows how it is used, and is another example of the way that cues use functions to delay creating the effect until you launch the cue.

**Comment by dandaka** [comment]
Works, thank you!
