### ISSUE TITLE
Sine beat goes from -0.5 to 1.5

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#22]
I was experimenting with sine-beat. I have experienced it went more than 1.0. And I see what I think is a bug. Please check, your graph is going from -0.5 to 1.5. But documentation is telling, that it goes from 0 to 1.0.

https://github.com/brunchboy/afterglow/blob/master/doc/oscillators.adoc#sine-oscillators

**Comment by brunchboy** [comment]
Yes, it is supposed to go from 0.0 to 1.0. As I said in my comment last night, trying things today will be brave, because I have not finished testing this stuff.

As it happens, I *did* run a test with some real lights this morning before going to work, and found and fixed this issue.

You need to do a lein -U deps to get the fix I pushed earlier this morning. (In my time zone anyway, where are you?)

Please let me know if that doesn’t solve the issue for you.

**Comment by dandaka** [comment]
Works fine with latest version! From Russia with :heart: My personal best experience with open source so far. Plz let me know your Paypal, so I could buy you a beer.

**Comment by brunchboy** [comment]
I am delighted to hear that! And in the case of this project, you were fortunate to have stumbled on to something that is in the early stages of being created, and which has become my passionate hobby. :fireworks:

If you really do want to send me something via Paypal, my account is [paypal.me/brunchboy](https://paypal.me/brunchboy)—and it would be nice timing, because I just used that account to contribute to Clojars, the site that hosts releases of Clojure projects like Afterglow, and to Cider, the Emacs environment I use for editing it. But your contributions to Afterglow simply by using it and giving me helpful feedback, suggestions, questions, and pull requests are already very much appreciated.
