### ISSUE TITLE
Inverted direction error

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#28]
Here is a log
https://gist.github.com/dandaka/c03adcd0b8b7db9b0a63

Here is latest code with fixtures definition
https://github.com/dandaka/lights-experiment/blob/master/src/lights/my_show.clj#L121-L128

What am I doing wrong?

**Comment by dandaka** [comment]
This code fails with a similar error:
```
(show/add-effect! :position
    (move/aim-effect "Center" (params/build-aim-param :x 0 :y 0 :z 5) (show/fixtures-named "head")))
```

https://gist.github.com/dandaka/5b285b104c979c9ec2fb

**Comment by brunchboy** [comment]
I don’t have time until later this evening to try pulling your code and testing a fix, but here is one thing I can see right away: You need to put the values for `:pan-center`, `:pan-half-circle`, `:tilt-center`, and `:tilt-half-circle` in the fixture definition itself, not in the call to `patch-fixture`. That is probably why Afterglow is hitting a null pointer exception looking for them.

You can look at an [example](https://github.com/brunchboy/afterglow/blob/master/src/afterglow/fixtures/blizzard.clj#L222-L223) from one of my own fixture definitions. This is a bit more complicated because my code allows you to pass different values when you call the fixture definition function, in case one particular fixture behaves slightly differently from the standard one. You can either copy that style and add those optional keyword arguments to your `jb-systems-sirius-8ch` fixture definition function, or keep it simple for now by just using the literal numbers in the map that it returns.

**Comment by dandaka** [comment]
Yep, thank you!

Now I have this, which looks like a bug
https://gist.github.com/dandaka/9bb02abe58e12b35d102

**Comment by brunchboy** [comment]
Whoops, I guess my PR was too late. What seems to be the bug? (But I really must stop looking at this until this evening.) Also, at some point you may want to turn of debug logging, and run at an info level, that will give you better performance. But it might be handy when first figuring out how these geometric transformations work.

**Comment by dandaka** [comment]
Looks like a bug — Clojure isn't stopping with errors (with my Sublime REPL) and after some time it hangs up. Maybe because of lots of debug information. I have to find where to turn this off, maybe it will solve the issue.

**Comment by dandaka** [comment]
`(timbre/set-config! {:level :warn})` solved the issue.

**Comment by dandaka** [comment]
I think information about debug level should be included somewhere. Maybe in the default project? Since I've found debug level only in core.clj, which is a strange place to look for :)

**Comment by brunchboy** [comment]
So I think the problem is that you started with the `my-show` example, which started out in my [afterglow-max](https://github.com/brunchboy/afterglow-max) project, where logging gets set up by my own framework code, rather than with my `examples.clj` namespace, which is what I experiment when running Afterglow from source. You did exactly the right thing when starting out to experiment with Afterglow as a library, but I messed up:

When I copied the `my-show` example out of afterglow-max as the basis of the example in the read-me, I never noticed that it was missing code to initialize the logging environment, which is present in the `examples.clj` namespace. So I will fix the example in the read-me, and I suggest you initialize logging in the same way in your project, by  calling `(core/init-logging)`, rather than the direct `(timbre/set-config! {:level :warn})` you added today.

Among other things, `init-logging` sets the default log level to `:info`, and configures Afterglow to log to a set of rotating log files in a `logs/` subdirectory of your project. You will need to create that directory for logging to happen, but then it will stay out of your way, and not grow to an unreasonable size. Whenever you want to watch the logs, you can `tail -f logs/afterglow.log`.

**Comment by dandaka** [comment]
Another thought. Why does Afterglow sends same error/debug messages on each frame of the show? My REPL hangs after 20k+ lines of text coming out super fast. Maybe there is a way to send 1 specific error only once?

**Comment by brunchboy** [comment]
I don’t know whether timbre has such a feature on the level of individual errors, but you can investigate its rate-throttling mechanisms in general, they do exist. However if you follow my suggestion to use `init-logging` they will not go into your REPL at all, and will instead be in size-limited rolled log files, causing no problems.

**Comment by dandaka** [comment]
You're right, switching to proper logger function made this problem non-existent. Thank you!

**Comment by brunchboy** [comment]
Great, thank you for pointing this out. Now that I have fixed the example, hopefully nobody else will run into the same problem.

Have you had any luck getting the pan and tilt channels of your moving head aiming correctly?

**Comment by dandaka** [comment]
I have to wait till tomorrow to have access to that fixtures.

**Comment by brunchboy** [comment]
I see! You are really living on the edge for this show. Hopefully my guess is correct. :grin:
