### ISSUE TITLE
Can't set variable in a cue

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#30]
I take example from #21:

https://github.com/brunchboy/afterglow/blob/master/doc/effects.adoc#variable-effects

My src is here:

https://github.com/dandaka/lights-experiment/blob/master/src/lights/my_show.clj

`> (light-sine)`
Lights are pulsing with sine

`> (afterglow.show/set-variable! :main-hue 120)`
Hue changes to green.

Press on a button with following code:
```
(ct/set-cue! (:cue-grid *show*) 0 0
    (cues/cue :color-var (fn [_](afterglow.effects/scene
      "Hue Red"
        (fn [_] (var-fx/variable-effect @var-binder :main-hue 0))
      )
    )))
```

Afterglow fails with this https://gist.github.com/dandaka/098b1180924b21dc2632

**Comment by brunchboy** [comment]
At a quick look, the contents of your `scene` call are not correct, you have another function wrapper in there, which only belongs outside where you have it in the`cue` call. In this case you don’t need the scene at all either, though. Compare the structure of your code with my example that you cited above. I think you want something like this:

```clojure
(ct/set-cue! (:cue-grid *show*) 0 0
               (cues/cue :set-main-hue
                         (fn [_] (var-fx/variable-effect @var-binder :hue-color 0))))

**Comment by brunchboy** [comment]
While scanning through your code, I notice that your [separate-colors]https://github.com/dandaka/lights-experiment/blob/master/src/lights/my_show.clj#L294-L303) effect still has calls to `show/add-effect!` in it, which it shouldn’t. You sent me a correct version as a pull request for the [documentation](https://github.com/brunchboy/afterglow/blob/master/doc/effects.adoc#multiple-colors), so you might want to fix the one in your own file. Even though it is labeled an experiment, it might trip you up someday if you leave it like that. :worried:

**Comment by brunchboy** [comment]
And once you are done with your show I can perhaps point you at the explanation of the `@var-binder` magic. In tiny summary, it builds a way for effects to set variables, rather than DMX values. You only need one of them for all of your `variable-effects` to work; it gives the effects a way to communicate with the low-level code that runs when rendering a frame of the show.

**Comment by dandaka** [comment]
Var setting works like fantastic, thank you! Is it possible to set txt label for such cues? I think I have used scenes to get text labels and lost in the process the ability to use your code.

Also, why can't scenes set variables? Do I have to choose between scenes and variables?

**Comment by brunchboy** [comment]
Yes, you can set the label, color, whatever you want for the cue. Those [optional keyword arguments](https://github.com/brunchboy/afterglow/blob/master/doc/cues.adoc#creating-cues) all follow the effect-creation function:

```clojure
(ct/set-cue! (:cue-grid *show*) 0 0
             (cues/cue :set-main-hue
                       (fn [_] (var-fx/variable-effect @var-binder :hue-color 0))
                       :short-name "My Label"))
```

If you don’t supply `:short-name`, the cue will use whatever name the effect is created with. See the link above for other parameters you can use to adjust the appearance of the cue in your cue grid or on your Ableton Push.

And no, you don’t have to choose; scenes can set variables, the scene was not the problem. The problem was the `(fn [_] ...)`: you were returning a function, not an effect.

I removed the scene to simplify things because you only need to return a single effect. Scenes are only needed when you want to combine multiple effects into one effect. If you want your cue to trigger other effects beyond setting the variable, you would then wrap it in a scene like so:

```clojure
(ct/set-cue! (:cue-grid *show*) 0 0
             (cues/cue :set-main-hue
                       (fn [_] (afterglow.effects.scene
                                "Doing several things"
                                (var-fx/variable-effect @var-binder :hue-color 0)
                                (some-other-effect blah blah)))))
```

> Warning, code snippets not not tested, I need tor run out the door. :blush:

**Comment by brunchboy** [comment]
Ah, and I now see that you were using the scene to change the effect name, because you didn’t know the other way to set the cue name! Ok, hopefully this example shows you the easier way.
