### ISSUE TITLE
Sparkle effect with dimmer?

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#35]
I want to use sparke with heads, that don't support colors, but they do support dimmer. Is it possible to use on such fixtures? I guess not.

What I understand from reading the docs is that sparke creates "random" flashes, while strobe creates "rhythmic" ones.

I think "sparkle" type of strobe could be a better alternative.

**Comment by brunchboy** [comment]
You’re right, the existing sparkle only works with RGB channels. I wrote it that way because some of my moving heads have delayed dimmer channels that could not respond fast enough. But my sparkle function is really just an example. Copy it, rename the new function dimmer-sparkle, and change it to create dimmer assigners rather than color assigners, and it will do what you want. (If you don’t have time, I could do that a few hours from now.)

**Comment by brunchboy** [comment]
Oh, and the strobe effect in Afterglow uses the native strobe capability of the fixture. Some fixtures support a variety of kinds of strobing, including random strobes, but most do not. Sparkle is purely an Afterglow thing.

**Comment by brunchboy** [comment]
Ok, it would have been way too hard for you to rewrite the old sparkle to a dimmer sparkle, it involves all different kinds of layers and interfaces of Afterglow. I think I am close, though, I just need to figure out why my dimmer assigners don’t seem to be having any effect…

**Comment by brunchboy** [comment]
Taking a break for a late dinner was a good thing, because right after I came back I was able to find my silly mistake, and now the new `dimmer-sparkle` effect is working. But it only works with normal lights where the dimmer has its own entire channel or two. I suppose you might need it to work with some of your weird lights which share the dimmer with other functions on the same channel, so I will expand it to support that before I push a release.

**Comment by brunchboy** [comment]
All right, with the snapshot I just deployed, you can create [sparkle](https://github.com/brunchboy/afterglow/blob/master/doc/effects.adoc#sparkle) effects for either RGB or non-RGB fixtures, and the new `dimmer-sparkle` should supposedly work with your fixtures that use only part of a channel for their dimmers. Please let me know! The documentation linked above explains how to use and combine these variations.

**Comment by dandaka** [comment]
Works great!
