### ISSUE TITLE
Expose Afterglow to MIDI inputs?

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#36]
I want to expose Afterglow to MIDI inputs from Ableton Live. So far I don't see Afterglow in the list of connected devices in Live. It looks like this:

![live-no-midi](https://cloud.githubusercontent.com/assets/2384694/11877284/f8e8bb4e-a4f6-11e5-845d-48c4bb221cc3.jpg)

Is it possible to wire MIDI inputs to Afterglow on one laptop?

**Comment by brunchboy** [comment]
It should be possible to have Afterglow pick up MIDI from Live, if Live creates a MIDI port in CoreMIDI. You won’t see Afterglow from Live, because Afterglow does not do that. But you should be able to see the Live port from Afterglow, as long as Live was running when you started Afterglow’s MIDI subsystem. (Because of limitations in Java’s MIDI support, which I am hoping to help another developer fix someday, you cannot currently add any devices after Java MIDI starts, and have them detected or usable).

I think you may have to set up a virtual MIDI bus for this to work. Ableton has a [support article](https://www.ableton.com/en/help/article/using-virtual-MIDI-buses-live/) about this.

**Comment by brunchboy** [comment]
And I can confirm that once I followed that support article to make the IAC device online in Audio MIDI Setup, Live saw it. I restarted Afterglow, and Afterglow could see it as well. I configured a track in Live as an External Instrument, and sent MIDI messages on that track, and Afterglow was able to identify them:

```clojure
(afterglow.midi/identify-mapping)
{:command :note-on, :channel 0, :note 68, :velocity 100,
 :device {:name "IAC Driver - Bus 1", :description "Bus 1"}}
```

**Comment by brunchboy** [comment]
So I’m dying to know, were you able to put together the show you were working on? How did it go? Capture any video? :sweat_drops:

**Comment by dandaka** [comment]
Show went great! Super positive feedback, but still lots of things to accomplish:

1. Didn't have time to get heads working properly. Used them only for strobing, which killed a big part of light in the venue.
2. Audio-reactive thing was working perfectly. But since musicians were dealing with their own technical problems (connection between Live and Maschine died midshow), I got zero MIDI on performance and had to degrade to plain simple sawtooth oscillation.
3. Live performance with musicians is super hard, because plan is unknown and improvising always falls behind. So I think we'll go to scripting all the scenes and launching them from Live to get seamless and meaningful lights performance.

Video was shot, but it will take time to edit. I will share for sure!

Thank you for your support, glad everything works out this good :+1:

**Comment by brunchboy** [comment]
That’s wonderful to hear! :tada: I can’t wait until you have a chance to edit the video. I would love to link to it from the Afterglow introduction once you feel it is ready.

**Comment by brunchboy** [comment]
Also, I love the directions that you are exploring. I think you are right that you will need to feed the audio through Live to get the level and frequency analysis done for now. (Or you could use Max, if you were already using it for something else, but as you said elsewhere, more components make more risk.) I also plan eventually to build that feature into Afterglow itself. Since you are already creating effects that depend on it, that might make me move faster in that direction.

**Comment by dandaka** [comment]
Yep. If you need videos for introduction, I could shot some while testing on the venue. Maybe some demos of different functions/effects, that could be achieved.

Also I have a friend, that has some experience in setting up lights in clubs (mostly on Sunlight platform). He is still laughing on my experiments. He has a valid point, that learning curve with Afterglow and experimenting is way harder, than "classic" light software. My plan is to take his inputs as requirements and try to implement them in Afterglow as "scaffolding" functions. As soon as I get some examples of how things are done there, maybe we could think about making shows easier with Afterglow.

**Comment by brunchboy** [comment]
Yes, your friend is right, if someone is looking for traditional lighting software, Afterglow is not the answer. It is what I created because traditional lighting software would not let me do the kinds of things I wanted; it is aimed at people who want to get down into the algorithm and tweak it in ways that commercial software simply cannot fathom.

**Comment by dandaka** [comment]
That is why I see great potential it using Afterglow for audio-reactive lights/video installations in clubs (as part of live/DJ performance) and as multimedia art installation.

**Comment by brunchboy** [comment]
Those sound like great ideas, yes. And once you get the geometric head movement aspect working you will have even more fun with them.

As for intro and demo videos, that would be wonderful. Every time I think about making some myself, I decide that I would rather spend the time adding more features instead. :blush:

**Comment by dandaka** [comment]
Not a problem for me. Can you set me up some kind of task/issue with your view on this? Some references from other products would be a good guide. Or just plain text script is also good.

**Comment by brunchboy** [comment]
OK, I can try to do that when I have some time to look over the documentation. First I would like us to close some of these issues, though. I think many of them are ready to be closed, but want to make sure for example that you update the way you are running code in cues to use the method I added for #34, because the earlier way I suggested in that discussion (running code in the effect-creation function of a cue) is a bad idea, because that function gets called when validating the cue as well as when launching it. So when you have a chance, please look over the open issues, and close the ones where you’ve been able to implement the suggestions.

**Comment by dandaka** [comment]
I will close them this week, takes time to test everything and update the documentation.

**Comment by dandaka** [comment]
Works, thank you! Also this IAC bus could be a workaround solution for disconnecting MIDI devices. They could run through Ableton.

**Comment by brunchboy** [comment]
Yes, everything takes time, I understand that very well. Thanks again for all your contributions!

And yes, as a short term workaround, you might be able to route your controllers through Ableton, although it would be somewhat tedious to set up, and I would think it would make it harder to identify them by name in Afterglow, although you could probably configure Live or Max to assign each one a different channel, and separate things out that way.

I don’t think that would work for me, though, when I am trying to drive an Ableton Push over MIDI, with support for the text display using MIDI SysEx, and so on. But the project that will hopefully replace MMJ, and hopefully soon support connecting MIDI devices after Java starts on a Macintosh, has been posted to GitHub, and I will be experimenting with it over the next few days: https://github.com/DerekCook/CoreMidi4J

**Comment by brunchboy** [comment]
I just finished my initial round of testing CoreMIDI4J with Afterglow, and it works as well as MMJ does (actually, better, it eliminates some lengthy pauses in setting up the MIDI environment), and it is open source, so now I can try to get it to detect when MIDI devices are connected after it is already up and running. :+1:
