### ISSUE TITLE
Step parameter could have :interval-ratio

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#42]
### Right now

`(afterglow.effects.params/build-step-param)` has only :interval key, that could be set to beat (x1) or phrase (x16). Everything else is impossible.

### Could be

User supplies :interval-ratio similar to oscillators. So he gets all kinds of step parameters.

**Comment by dandaka** [comment]
My goal was to create hue, that increases in time (so making a loop at the 360). Maybe it was not an intended design use (since I see you use these parameters with chases), but might be a good idea to extend its use cases.

**Comment by brunchboy** [comment]
Actually `:interval` can currently either be `:beat` (the default), `:bar` (4 beats, for the standard metronome), or `:phrase` (4 beats * 8 bars, for the standard metronome). Offering a beat ratio here is an interesting idea, lets leave this open to investigate how hard that will be.

Is your hue increasing in a discontinuous way, i.e. does it jump? If so, that makes sense to use a step parameter. Otherwise, since hue loops at 360, as you noted, you can just use a sawtooth oscillated parameter, ranging from 0 to 360.

**Comment by dandaka** [comment]
Yep, it does jump. I found it nice to have radical changes in sync with metronome.

**Comment by brunchboy** [comment]
That makes sense, I have created similar effects with chases, but now that step parameters have been invented, this is a nice idea, especially because of the configurable smoothing they can give you. I simply was focused entirely on driving chases when creating step parameters, and didn’t think of it. Hopefully it will be fairly straightforward to add.

**Comment by brunchboy** [comment]
My head hurts… figuring out the formulas for adding interval ratios to step parameters is more difficult than I hoped. I had forgotten how many days I scribbled graphs and equations before I got them right for oscillators. But I think I am on the right track now, I will break for the night and try again with a fresh mind tomorrow.

**Comment by brunchboy** [comment]
All right, I have this working for you! Shortly after I walked away, I had the insight I needed to get the math basically right, then I just had to sort out some discontinuities. I forgot to reference this issue in the commit, but it is b78fd4e09c7732e4cb586b1f6c58b09d64a66807. And I just updated the snapshot on Clojars to include it.

**Comment by brunchboy** [comment]
And I just pushed another commit (and snapshot) that adds the ability for step parameters to be built using dynamic parameters, because I figured you would want that flexibility sooner or later… :grin:

**Comment by dandaka** [comment]
Works fine, thank you very much!

**Comment by brunchboy** [comment]
Thanks for testing and confirming that.
