### ISSUE TITLE
Mixing dimmable with non-dimmable fixtures — virtual dimmers?

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#43]
Some lights have dimmers. Some don't. Since you have to control all the lights at the same time, you have following options:

1. Don't use generic :color and :dimmer effects in cue. Create new one (say :dimmer-color), where you specify both :color and :dimmer effects for all lights in the setup.
2. Have ability to specify :dimmer for lights without dimmer channel. Apply transformation to colors, so user could dim lights without dimmer.

What is your usual solution in these cases? I have seen you don't control all dimmers and colors at the same time. So you have to activate multiple cues to achieve a desired effect?

**Comment by brunchboy** [comment]
I think your lights without dimmers are very unusual. I have not encountered any like that so far. For most of my lights, I use dimmers to set the overall brightness level of the show, primarily through the show grand master, and then use RGB (and white/amber/UV) channels to vary brightness for rhythmic effects. So yes, I often combine a dimmer cue with a color cue to get a particular look, and achieve combinatorial growth in the number of different looks I can achieve with a given set of cues.

Your idea of a variation on a dimmer/color effect which could simulate a dimmer channel via the color/intensity channels for lights which lack dimmers is an interesting one, but I would not want to build that ability into most effects, because I think it would be slowing them down for what is a rare situation. So yes, let’s put it on the to-do list for someday, and I would certainly accept a pull request for such an effect, but I have other things to deal with first. Right now I have unexpectedly been loaned a version 2 Ableton Push, and can see that it does not work at all with Afterglow, so I am trying quickly to investigate how hard it will be to support.

**Comment by dandaka** [comment]
Got your point! I will look into mixing `:color` with `:dimmer` effects into one cue and see, how useful is that solution. Good luck with Push!

**Comment by brunchboy** [comment]
Thanks! I still want to be sure not to lose your idea of virtual dimmer effects, though, so I shall add a link to this discussion into the to-do list.

**Comment by brunchboy** [comment]
And sad news about Push 2, it is looking like the display does not use MIDI for updates, so supporting it may be very difficult or impossible.

**Comment by dandaka** [comment]
Check this http://sigabort.co/p2d

**Comment by brunchboy** [comment]
Interesting! It is not hopeless then. I will send them a note, to see if they can share any information. They may not be happy with an open-source project like this one, however. And it looks like it is native code, not a Java library so far, which would complicate things. But someday the Push 2 display may be accessible… with much work. Thanks for the link!

**Comment by brunchboy** [comment]
The only support I have received from Ableton so far has been “use MIDI Monitor to watch how it works” which does not address my two issues, of the display (which is not using MIDI), and setting pad colors to arbitrary RGB values, which used a SysEx message that Live is not sending so I can’t watch for it. Sigh.

**Comment by brunchboy** [comment]
I am reopening this issue because during my swim today, I thought of a clean way to create virtual dimmer effects for you, so I plan to implement them. They will run on their own, not complicate existing dimmer or color effects, so there is no harm in having them available for fixtures like yours which lack dimmers. They will be color effects that modify the results of your other color effects (the way real dimmer effects work in tandem with color effects), so you will need to assign them a higher priority than the color effects they adjust, and only run the virtual dimmer effects on the fixtures which lack real dimmer channels. But the virtual dimmer effects will honor the dimmer master chain, and let all of your dimmer effects, both real and virtual, honor a global show brightness level through that mechanism.

**Comment by brunchboy** [comment]
All right, I have virtual dimmers working, and in an even more convenient way than I hoped. I still need to write up documentation, but in the latest snapshot, if you call [dimmmer-effect](http://deepsymmetry.org/afterglow/doc/afterglow.effects.dimmer.html#var-dimmer-effect) with `:add-virtual-dimmers?` `true` and `:htp?` `false` (because virtual dimmers don’t use actual dimmer channels, they are incompatible with highest-takes-precedence rules), it will create a set of virtual dimmer assigners for any fixtures like yours which are RGB capable but lack dimmer channels. These assigners will modify any existing color effect they find for those fixtures to dim the color as if there was a dimmer on the fixtures. That means you need to assign this dimmer effect a higher priority than any color effects you want to combine it with, so it runs later and can modify the output of the color effects. But it works, and honors the dimmer master settings just like real dimmer effects. So you can pretend your lights have dimmers and have them participate in dimmer effects with the ones that do.

**Comment by brunchboy** [comment]
All right, I have written up the virtual dimmer [documentation](https://github.com/brunchboy/afterglow/blob/master/doc/effects.adoc#virtual-dimmers). Please give them a try, and let me know how they work with your fixtures! Although it took me a while to figure out a good way to address this need, I am glad you brought it up, because I think we have a very good solution now. It always makes me happy when the underlying design turns out to be able to accommodate things I did not anticipate, and in a good way.

**Comment by dandaka** [comment]
Works fine, thank you very much for this! Helps a lot!

**Comment by brunchboy** [comment]
That’s great! Thanks for the idea, and for letting me know the implementation works for you. :+1:
