### ISSUE TITLE
Web interface broken 500 error on show URL

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#45]
localhost:16000 works fine
localhost:16000/console works fine
http://localhost:16000/show/1 gives 500

Error: 500
Something very bad has happened!
We've dispatched a team of highly trained gnomes to take care of the problem.

Log is here:
https://gist.github.com/dandaka/7fa57567b524065d1a14

**Comment by brunchboy** [comment]
That looks to me like perhaps a Clojure version incompatibility. My pre-release snapshot is using release candidates of Clojure 1.8 at the moment, and they have changed over time.

I would suggest trying the following: Update your `project.clj` to depend on the same pre-release of Clojure that the current pre-release of Afterglow is building against: `[org.clojure/clojure "1.8.0-RC4"]` and then run

    lein clean
    lein -U deps

and try again…

Once Clojure 1.8 is released this will stop being an issue. (And once Afterglow slows down enough that you can run release versions, you will be safer still. But there is too much good stuff coming in the pre-release versions today. I hope to build another release this weekend, and since Clojure 1.8 is unlikely to be released yet, the Afterglow release will be built against Clojure 1.7.)

**Comment by dandaka** [comment]
Works fine, thank you!
