### ISSUE TITLE
First run: All channels involved?

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#6]
**Right now***

First time user is starting your example. He has to understand, how fixtures are working. And it is not and easy task.

Otherwise he thinks, that tool is not working.

**Should be**

On first start of the show, use all DMX channels in Universe 1 to change their values in time. User gets immediate feedback, that tool is working.

**Comment by brunchboy** [comment]
That’s fundamentally opposed to the way afterglow works, though… the idea of my walkthrough is that you will use the sample fixtures in the sample show and watch the corresponding DMX values change using the OLA web console, available from the Afterglow web console home page, or at http://localhost:9090/new/

That will let you verify that Afterglow is sending DMX values to OLA, even if it doesn't do anything sensible with your actual lights yet.

When you want to set particular DMX values that you know will control your physical fixtures, to make sure that OLA and DMX are working at a low level, you can use OLA’s faders directly. For example, for Universe 1, those would be at http://localhost:9090/new/#/universe/1/faders (but make sure to stop any running Afterglow show that is sending output to that universe when you want to play with the faders manually).

Then when you are ready to have Afterglow controlling your actual fixtures, the next step is to write some fixture definitions. As you have noted, that is challenging, which is why I offer to help people while we are building up an initial library of fixtures, and also why I wrote the tool which can convert fixtures from the QLC+ library, as described in the [wiki](https://github.com/brunchboy/afterglow/wiki/Questions#defining-fixtures).

With all that said, however, here is another idea for you. Because you're not worried about doing fancy things with spatial positioning yet, you can achieve more or less what you described in this Issue by using `patch-fixture-group!` to patch a bunch of generic dimmer fixtures into your show. For example, this would create 50 of them at addresses 1 to 50 in Universe 1:

```clojure
(show/patch-fixture-group! :test (afterglow.fixtures/generic-dimmmer) 1 1 50)
```

Now your show has fifty "fixtures" in it, named `:test-1`, `:test-2`, ... `:test-50`. Each of them has a single dimmer channel and nothing else. Now, here is how you could set all fifty those channels to 100:

```clojure
(show/add-effect! :dimmers (dimmer-effect 100 (show/all-fixtures)))
```

You can repeat that line with different numbers to set all the channels to a different level. When you want to kill the effect, just evaluate:

```clojure
(show/clear-effects!)
```

And, of course, if you really wanted to affect *every* channel in your universe, you could have used a value of 512 rather than 50 in the `patch-fixture-group!` call.

Does that help you get any further? I hope so, but once we start making progress on your fixture definitions is when the fun will really begin!

**Comment by dandaka** [comment]
Yep, it helps. I definitely would use this code, when starting to understand, how Afterglow works.

**Comment by brunchboy** [comment]
Great! I’ll have to try to figure out how to organize that into a separate section of the documentation when I have a chance.
